//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteFunc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/AcessoADados.Funcionarios")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarteiraProfissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ComissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecaoEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieCarteiraProfisionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneResidencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaEleitoralField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarteiraProfissional {
            get {
                return this.CarteiraProfissionalField;
            }
            set {
                if ((object.ReferenceEquals(this.CarteiraProfissionalField, value) != true)) {
                    this.CarteiraProfissionalField = value;
                    this.RaisePropertyChanged("CarteiraProfissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Comissao {
            get {
                return this.ComissaoField;
            }
            set {
                if ((this.ComissaoField.Equals(value) != true)) {
                    this.ComissaoField = value;
                    this.RaisePropertyChanged("Comissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nacionalidade {
            get {
                return this.NacionalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadeField, value) != true)) {
                    this.NacionalidadeField = value;
                    this.RaisePropertyChanged("Nacionalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroEndereco {
            get {
                return this.NumeroEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroEnderecoField, value) != true)) {
                    this.NumeroEnderecoField = value;
                    this.RaisePropertyChanged("NumeroEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBS {
            get {
                return this.OBSField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSField, value) != true)) {
                    this.OBSField = value;
                    this.RaisePropertyChanged("OBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIS {
            get {
                return this.PISField;
            }
            set {
                if ((object.ReferenceEquals(this.PISField, value) != true)) {
                    this.PISField = value;
                    this.RaisePropertyChanged("PIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecaoEleitor {
            get {
                return this.SecaoEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.SecaoEleitorField, value) != true)) {
                    this.SecaoEleitorField = value;
                    this.RaisePropertyChanged("SecaoEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieCarteiraProfisional {
            get {
                return this.SerieCarteiraProfisionalField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieCarteiraProfisionalField, value) != true)) {
                    this.SerieCarteiraProfisionalField = value;
                    this.RaisePropertyChanged("SerieCarteiraProfisional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneCelular {
            get {
                return this.TelefoneCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelularField, value) != true)) {
                    this.TelefoneCelularField = value;
                    this.RaisePropertyChanged("TelefoneCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneResidencial {
            get {
                return this.TelefoneResidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneResidencialField, value) != true)) {
                    this.TelefoneResidencialField = value;
                    this.RaisePropertyChanged("TelefoneResidencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEndereco {
            get {
                return this.TipoEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEnderecoField, value) != true)) {
                    this.TipoEnderecoField = value;
                    this.RaisePropertyChanged("TipoEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TituloEleitor {
            get {
                return this.TituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloEleitorField, value) != true)) {
                    this.TituloEleitorField = value;
                    this.RaisePropertyChanged("TituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZonaEleitoral {
            get {
                return this.ZonaEleitoralField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaEleitoralField, value) != true)) {
                    this.ZonaEleitoralField = value;
                    this.RaisePropertyChanged("ZonaEleitoral");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarFuncionarioDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarFuncionarioDataAccessResponse")]
        TesteFunc.ServiceReference1.Funcionario[] ConsultarFuncionarioDataAccess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarFuncionarioDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarFuncionarioDataAccessResponse")]
        System.Threading.Tasks.Task<TesteFunc.ServiceReference1.Funcionario[]> ConsultarFuncionarioDataAccessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarFuncionario", ReplyAction="http://tempuri.org/IService1/SelecionarFuncionarioResponse")]
        TesteFunc.ServiceReference1.Funcionario SelecionarFuncionario(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarFuncionario", ReplyAction="http://tempuri.org/IService1/SelecionarFuncionarioResponse")]
        System.Threading.Tasks.Task<TesteFunc.ServiceReference1.Funcionario> SelecionarFuncionarioAsync(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirFuncionario", ReplyAction="http://tempuri.org/IService1/ExcluirFuncionarioResponse")]
        void ExcluirFuncionario(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirFuncionario", ReplyAction="http://tempuri.org/IService1/ExcluirFuncionarioResponse")]
        System.Threading.Tasks.Task ExcluirFuncionarioAsync(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarFuncionario", ReplyAction="http://tempuri.org/IService1/AtualizarFuncionarioResponse")]
        void AtualizarFuncionario(TesteFunc.ServiceReference1.Funcionario DadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarFuncionario", ReplyAction="http://tempuri.org/IService1/AtualizarFuncionarioResponse")]
        System.Threading.Tasks.Task AtualizarFuncionarioAsync(TesteFunc.ServiceReference1.Funcionario DadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirFuncionario", ReplyAction="http://tempuri.org/IService1/InserirFuncionarioResponse")]
        void InserirFuncionario(TesteFunc.ServiceReference1.Funcionario dadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirFuncionario", ReplyAction="http://tempuri.org/IService1/InserirFuncionarioResponse")]
        System.Threading.Tasks.Task InserirFuncionarioAsync(TesteFunc.ServiceReference1.Funcionario dadosFuncionario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TesteFunc.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TesteFunc.ServiceReference1.IService1>, TesteFunc.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TesteFunc.ServiceReference1.Funcionario[] ConsultarFuncionarioDataAccess() {
            return base.Channel.ConsultarFuncionarioDataAccess();
        }
        
        public System.Threading.Tasks.Task<TesteFunc.ServiceReference1.Funcionario[]> ConsultarFuncionarioDataAccessAsync() {
            return base.Channel.ConsultarFuncionarioDataAccessAsync();
        }
        
        public TesteFunc.ServiceReference1.Funcionario SelecionarFuncionario(int IdFuncionario) {
            return base.Channel.SelecionarFuncionario(IdFuncionario);
        }
        
        public System.Threading.Tasks.Task<TesteFunc.ServiceReference1.Funcionario> SelecionarFuncionarioAsync(int IdFuncionario) {
            return base.Channel.SelecionarFuncionarioAsync(IdFuncionario);
        }
        
        public void ExcluirFuncionario(int IdFuncionario) {
            base.Channel.ExcluirFuncionario(IdFuncionario);
        }
        
        public System.Threading.Tasks.Task ExcluirFuncionarioAsync(int IdFuncionario) {
            return base.Channel.ExcluirFuncionarioAsync(IdFuncionario);
        }
        
        public void AtualizarFuncionario(TesteFunc.ServiceReference1.Funcionario DadosFuncionario) {
            base.Channel.AtualizarFuncionario(DadosFuncionario);
        }
        
        public System.Threading.Tasks.Task AtualizarFuncionarioAsync(TesteFunc.ServiceReference1.Funcionario DadosFuncionario) {
            return base.Channel.AtualizarFuncionarioAsync(DadosFuncionario);
        }
        
        public void InserirFuncionario(TesteFunc.ServiceReference1.Funcionario dadosFuncionario) {
            base.Channel.InserirFuncionario(dadosFuncionario);
        }
        
        public System.Threading.Tasks.Task InserirFuncionarioAsync(TesteFunc.ServiceReference1.Funcionario dadosFuncionario) {
            return base.Channel.InserirFuncionarioAsync(dadosFuncionario);
        }
    }
}
