//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcessoADados.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fornecedor", Namespace="http://schemas.datacontract.org/2004/07/AcessoADados.Compras")]
    [System.SerializableAttribute()]
    public partial class Fornecedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailRepresentanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeRepresentanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneCelularRepresentanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneFixoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailEmpresa {
            get {
                return this.EmailEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailEmpresaField, value) != true)) {
                    this.EmailEmpresaField = value;
                    this.RaisePropertyChanged("EmailEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailRepresentante {
            get {
                return this.EmailRepresentanteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailRepresentanteField, value) != true)) {
                    this.EmailRepresentanteField = value;
                    this.RaisePropertyChanged("EmailRepresentante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePage {
            get {
                return this.HomePageField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePageField, value) != true)) {
                    this.HomePageField = value;
                    this.RaisePropertyChanged("HomePage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IE {
            get {
                return this.IEField;
            }
            set {
                if ((object.ReferenceEquals(this.IEField, value) != true)) {
                    this.IEField = value;
                    this.RaisePropertyChanged("IE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFornecedor {
            get {
                return this.IdFornecedorField;
            }
            set {
                if ((this.IdFornecedorField.Equals(value) != true)) {
                    this.IdFornecedorField = value;
                    this.RaisePropertyChanged("IdFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeEmpresa {
            get {
                return this.NomeEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeEmpresaField, value) != true)) {
                    this.NomeEmpresaField = value;
                    this.RaisePropertyChanged("NomeEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeRepresentante {
            get {
                return this.NomeRepresentanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeRepresentanteField, value) != true)) {
                    this.NomeRepresentanteField = value;
                    this.RaisePropertyChanged("NomeRepresentante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneCelularRepresentante {
            get {
                return this.TelefoneCelularRepresentanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelularRepresentanteField, value) != true)) {
                    this.TelefoneCelularRepresentanteField = value;
                    this.RaisePropertyChanged("TelefoneCelularRepresentante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneFixo {
            get {
                return this.TelefoneFixoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneFixoField, value) != true)) {
                    this.TelefoneFixoField = value;
                    this.RaisePropertyChanged("TelefoneFixo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/AcessoADados.Vendas")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneResidencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IE {
            get {
                return this.IEField;
            }
            set {
                if ((object.ReferenceEquals(this.IEField, value) != true)) {
                    this.IEField = value;
                    this.RaisePropertyChanged("IE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneCelular {
            get {
                return this.TelefoneCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelularField, value) != true)) {
                    this.TelefoneCelularField = value;
                    this.RaisePropertyChanged("TelefoneCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneComercial {
            get {
                return this.TelefoneComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneComercialField, value) != true)) {
                    this.TelefoneComercialField = value;
                    this.RaisePropertyChanged("TelefoneComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneResidencial {
            get {
                return this.TelefoneResidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneResidencialField, value) != true)) {
                    this.TelefoneResidencialField = value;
                    this.RaisePropertyChanged("TelefoneResidencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEndereco {
            get {
                return this.TipoEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEnderecoField, value) != true)) {
                    this.TipoEnderecoField = value;
                    this.RaisePropertyChanged("TipoEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/AcessoADados.Funcionarios")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarteiraProfissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ComissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecaoEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieCarteiraProfisionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneResidencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloEleitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaEleitoralField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarteiraProfissional {
            get {
                return this.CarteiraProfissionalField;
            }
            set {
                if ((object.ReferenceEquals(this.CarteiraProfissionalField, value) != true)) {
                    this.CarteiraProfissionalField = value;
                    this.RaisePropertyChanged("CarteiraProfissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Comissao {
            get {
                return this.ComissaoField;
            }
            set {
                if ((this.ComissaoField.Equals(value) != true)) {
                    this.ComissaoField = value;
                    this.RaisePropertyChanged("Comissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nacionalidade {
            get {
                return this.NacionalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadeField, value) != true)) {
                    this.NacionalidadeField = value;
                    this.RaisePropertyChanged("Nacionalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroEndereco {
            get {
                return this.NumeroEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroEnderecoField, value) != true)) {
                    this.NumeroEnderecoField = value;
                    this.RaisePropertyChanged("NumeroEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBS {
            get {
                return this.OBSField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSField, value) != true)) {
                    this.OBSField = value;
                    this.RaisePropertyChanged("OBS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIS {
            get {
                return this.PISField;
            }
            set {
                if ((object.ReferenceEquals(this.PISField, value) != true)) {
                    this.PISField = value;
                    this.RaisePropertyChanged("PIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecaoEleitor {
            get {
                return this.SecaoEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.SecaoEleitorField, value) != true)) {
                    this.SecaoEleitorField = value;
                    this.RaisePropertyChanged("SecaoEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieCarteiraProfisional {
            get {
                return this.SerieCarteiraProfisionalField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieCarteiraProfisionalField, value) != true)) {
                    this.SerieCarteiraProfisionalField = value;
                    this.RaisePropertyChanged("SerieCarteiraProfisional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneCelular {
            get {
                return this.TelefoneCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelularField, value) != true)) {
                    this.TelefoneCelularField = value;
                    this.RaisePropertyChanged("TelefoneCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneResidencial {
            get {
                return this.TelefoneResidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneResidencialField, value) != true)) {
                    this.TelefoneResidencialField = value;
                    this.RaisePropertyChanged("TelefoneResidencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEndereco {
            get {
                return this.TipoEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEnderecoField, value) != true)) {
                    this.TipoEnderecoField = value;
                    this.RaisePropertyChanged("TipoEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TituloEleitor {
            get {
                return this.TituloEleitorField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloEleitorField, value) != true)) {
                    this.TituloEleitorField = value;
                    this.RaisePropertyChanged("TituloEleitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZonaEleitoral {
            get {
                return this.ZonaEleitoralField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaEleitoralField, value) != true)) {
                    this.ZonaEleitoralField = value;
                    this.RaisePropertyChanged("ZonaEleitoral");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/AcessoADados.Compras")]
    [System.SerializableAttribute()]
    public partial class Compra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompraDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraFornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdItensCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdItensCompraComraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaturezaOperacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoCustoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TamanhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorTotalCompraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompraDescricao {
            get {
                return this.CompraDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompraDescricaoField, value) != true)) {
                    this.CompraDescricaoField = value;
                    this.RaisePropertyChanged("CompraDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cor {
            get {
                return this.CorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorField, value) != true)) {
                    this.CorField = value;
                    this.RaisePropertyChanged("Cor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCompra {
            get {
                return this.DataCompraField;
            }
            set {
                if ((this.DataCompraField.Equals(value) != true)) {
                    this.DataCompraField = value;
                    this.RaisePropertyChanged("DataCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoModelo {
            get {
                return this.DescricaoModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoModeloField, value) != true)) {
                    this.DescricaoModeloField = value;
                    this.RaisePropertyChanged("DescricaoModelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompra {
            get {
                return this.IdCompraField;
            }
            set {
                if ((this.IdCompraField.Equals(value) != true)) {
                    this.IdCompraField = value;
                    this.RaisePropertyChanged("IdCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompraFornecedor {
            get {
                return this.IdCompraFornecedorField;
            }
            set {
                if ((this.IdCompraFornecedorField.Equals(value) != true)) {
                    this.IdCompraFornecedorField = value;
                    this.RaisePropertyChanged("IdCompraFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdItensCompra {
            get {
                return this.IdItensCompraField;
            }
            set {
                if ((this.IdItensCompraField.Equals(value) != true)) {
                    this.IdItensCompraField = value;
                    this.RaisePropertyChanged("IdItensCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdItensCompraComra {
            get {
                return this.IdItensCompraComraField;
            }
            set {
                if ((this.IdItensCompraComraField.Equals(value) != true)) {
                    this.IdItensCompraComraField = value;
                    this.RaisePropertyChanged("IdItensCompraComra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaturezaOperacao {
            get {
                return this.NaturezaOperacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NaturezaOperacaoField, value) != true)) {
                    this.NaturezaOperacaoField = value;
                    this.RaisePropertyChanged("NaturezaOperacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoCusto {
            get {
                return this.PrecoCustoField;
            }
            set {
                if ((this.PrecoCustoField.Equals(value) != true)) {
                    this.PrecoCustoField = value;
                    this.RaisePropertyChanged("PrecoCusto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeTotal {
            get {
                return this.QuantidadeTotalField;
            }
            set {
                if ((this.QuantidadeTotalField.Equals(value) != true)) {
                    this.QuantidadeTotalField = value;
                    this.RaisePropertyChanged("QuantidadeTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tamanho {
            get {
                return this.TamanhoField;
            }
            set {
                if ((object.ReferenceEquals(this.TamanhoField, value) != true)) {
                    this.TamanhoField = value;
                    this.RaisePropertyChanged("Tamanho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorTotalCompra {
            get {
                return this.ValorTotalCompraField;
            }
            set {
                if ((this.ValorTotalCompraField.Equals(value) != true)) {
                    this.ValorTotalCompraField = value;
                    this.RaisePropertyChanged("ValorTotalCompra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarFornecedorDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarFornecedorDataAccessResponse")]
        AcessoADados.ServiceReference1.Fornecedor[] ConsultarFornecedorDataAccess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarFornecedorDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarFornecedorDataAccessResponse")]
        System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Fornecedor[]> ConsultarFornecedorDataAccessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarFornecedor", ReplyAction="http://tempuri.org/IService1/SelecionarFornecedorResponse")]
        AcessoADados.ServiceReference1.Fornecedor SelecionarFornecedor(int IdFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarFornecedor", ReplyAction="http://tempuri.org/IService1/SelecionarFornecedorResponse")]
        System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Fornecedor> SelecionarFornecedorAsync(int IdFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirFornecedor", ReplyAction="http://tempuri.org/IService1/ExcluirFornecedorResponse")]
        void ExcluirFornecedor(int IdFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirFornecedor", ReplyAction="http://tempuri.org/IService1/ExcluirFornecedorResponse")]
        System.Threading.Tasks.Task ExcluirFornecedorAsync(int IdFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarFornecedor", ReplyAction="http://tempuri.org/IService1/AtualizarFornecedorResponse")]
        void AtualizarFornecedor(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarFornecedor", ReplyAction="http://tempuri.org/IService1/AtualizarFornecedorResponse")]
        System.Threading.Tasks.Task AtualizarFornecedorAsync(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirFornecedor", ReplyAction="http://tempuri.org/IService1/InserirFornecedorResponse")]
        void InserirFornecedor(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirFornecedor", ReplyAction="http://tempuri.org/IService1/InserirFornecedorResponse")]
        System.Threading.Tasks.Task InserirFornecedorAsync(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarClienteDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarClienteDataAccessResponse")]
        AcessoADados.ServiceReference1.Cliente[] ConsultarClienteDataAccess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarClienteDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarClienteDataAccessResponse")]
        System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Cliente[]> ConsultarClienteDataAccessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarCliente", ReplyAction="http://tempuri.org/IService1/SelecionarClienteResponse")]
        AcessoADados.ServiceReference1.Cliente SelecionarCliente(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarCliente", ReplyAction="http://tempuri.org/IService1/SelecionarClienteResponse")]
        System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Cliente> SelecionarClienteAsync(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirCliente", ReplyAction="http://tempuri.org/IService1/ExcluirClienteResponse")]
        void ExcluirCliente(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirCliente", ReplyAction="http://tempuri.org/IService1/ExcluirClienteResponse")]
        System.Threading.Tasks.Task ExcluirClienteAsync(int IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarCliente", ReplyAction="http://tempuri.org/IService1/AtualizarClienteResponse")]
        void AtualizarCliente(AcessoADados.ServiceReference1.Cliente DadosCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarCliente", ReplyAction="http://tempuri.org/IService1/AtualizarClienteResponse")]
        System.Threading.Tasks.Task AtualizarClienteAsync(AcessoADados.ServiceReference1.Cliente DadosCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirCliente", ReplyAction="http://tempuri.org/IService1/InserirClienteResponse")]
        void InserirCliente(AcessoADados.ServiceReference1.Cliente dadosCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirCliente", ReplyAction="http://tempuri.org/IService1/InserirClienteResponse")]
        System.Threading.Tasks.Task InserirClienteAsync(AcessoADados.ServiceReference1.Cliente dadosCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarFuncionarioDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarFuncionarioDataAccessResponse")]
        AcessoADados.ServiceReference1.Funcionario[] ConsultarFuncionarioDataAccess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarFuncionarioDataAccess", ReplyAction="http://tempuri.org/IService1/ConsultarFuncionarioDataAccessResponse")]
        System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Funcionario[]> ConsultarFuncionarioDataAccessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarFuncionario", ReplyAction="http://tempuri.org/IService1/SelecionarFuncionarioResponse")]
        AcessoADados.ServiceReference1.Funcionario SelecionarFuncionario(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelecionarFuncionario", ReplyAction="http://tempuri.org/IService1/SelecionarFuncionarioResponse")]
        System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Funcionario> SelecionarFuncionarioAsync(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirFuncionario", ReplyAction="http://tempuri.org/IService1/ExcluirFuncionarioResponse")]
        void ExcluirFuncionario(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirFuncionario", ReplyAction="http://tempuri.org/IService1/ExcluirFuncionarioResponse")]
        System.Threading.Tasks.Task ExcluirFuncionarioAsync(int IdFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarFuncionario", ReplyAction="http://tempuri.org/IService1/AtualizarFuncionarioResponse")]
        void AtualizarFuncionario(AcessoADados.ServiceReference1.Funcionario DadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarFuncionario", ReplyAction="http://tempuri.org/IService1/AtualizarFuncionarioResponse")]
        System.Threading.Tasks.Task AtualizarFuncionarioAsync(AcessoADados.ServiceReference1.Funcionario DadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirFuncionario", ReplyAction="http://tempuri.org/IService1/InserirFuncionarioResponse")]
        void InserirFuncionario(AcessoADados.ServiceReference1.Funcionario DadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirFuncionario", ReplyAction="http://tempuri.org/IService1/InserirFuncionarioResponse")]
        System.Threading.Tasks.Task InserirFuncionarioAsync(AcessoADados.ServiceReference1.Funcionario DadosFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirCompra", ReplyAction="http://tempuri.org/IService1/InserirCompraResponse")]
        void InserirCompra(string IdFornecedor, string IdCompra, AcessoADados.ServiceReference1.Compra DadosCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InserirCompra", ReplyAction="http://tempuri.org/IService1/InserirCompraResponse")]
        System.Threading.Tasks.Task InserirCompraAsync(string IdFornecedor, string IdCompra, AcessoADados.ServiceReference1.Compra DadosCompra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AcessoADados.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AcessoADados.ServiceReference1.IService1>, AcessoADados.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AcessoADados.ServiceReference1.Fornecedor[] ConsultarFornecedorDataAccess() {
            return base.Channel.ConsultarFornecedorDataAccess();
        }
        
        public System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Fornecedor[]> ConsultarFornecedorDataAccessAsync() {
            return base.Channel.ConsultarFornecedorDataAccessAsync();
        }
        
        public AcessoADados.ServiceReference1.Fornecedor SelecionarFornecedor(int IdFornecedor) {
            return base.Channel.SelecionarFornecedor(IdFornecedor);
        }
        
        public System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Fornecedor> SelecionarFornecedorAsync(int IdFornecedor) {
            return base.Channel.SelecionarFornecedorAsync(IdFornecedor);
        }
        
        public void ExcluirFornecedor(int IdFornecedor) {
            base.Channel.ExcluirFornecedor(IdFornecedor);
        }
        
        public System.Threading.Tasks.Task ExcluirFornecedorAsync(int IdFornecedor) {
            return base.Channel.ExcluirFornecedorAsync(IdFornecedor);
        }
        
        public void AtualizarFornecedor(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor) {
            base.Channel.AtualizarFornecedor(DadosFornecedor);
        }
        
        public System.Threading.Tasks.Task AtualizarFornecedorAsync(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor) {
            return base.Channel.AtualizarFornecedorAsync(DadosFornecedor);
        }
        
        public void InserirFornecedor(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor) {
            base.Channel.InserirFornecedor(DadosFornecedor);
        }
        
        public System.Threading.Tasks.Task InserirFornecedorAsync(AcessoADados.ServiceReference1.Fornecedor DadosFornecedor) {
            return base.Channel.InserirFornecedorAsync(DadosFornecedor);
        }
        
        public AcessoADados.ServiceReference1.Cliente[] ConsultarClienteDataAccess() {
            return base.Channel.ConsultarClienteDataAccess();
        }
        
        public System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Cliente[]> ConsultarClienteDataAccessAsync() {
            return base.Channel.ConsultarClienteDataAccessAsync();
        }
        
        public AcessoADados.ServiceReference1.Cliente SelecionarCliente(int IdCliente) {
            return base.Channel.SelecionarCliente(IdCliente);
        }
        
        public System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Cliente> SelecionarClienteAsync(int IdCliente) {
            return base.Channel.SelecionarClienteAsync(IdCliente);
        }
        
        public void ExcluirCliente(int IdCliente) {
            base.Channel.ExcluirCliente(IdCliente);
        }
        
        public System.Threading.Tasks.Task ExcluirClienteAsync(int IdCliente) {
            return base.Channel.ExcluirClienteAsync(IdCliente);
        }
        
        public void AtualizarCliente(AcessoADados.ServiceReference1.Cliente DadosCliente) {
            base.Channel.AtualizarCliente(DadosCliente);
        }
        
        public System.Threading.Tasks.Task AtualizarClienteAsync(AcessoADados.ServiceReference1.Cliente DadosCliente) {
            return base.Channel.AtualizarClienteAsync(DadosCliente);
        }
        
        public void InserirCliente(AcessoADados.ServiceReference1.Cliente dadosCliente) {
            base.Channel.InserirCliente(dadosCliente);
        }
        
        public System.Threading.Tasks.Task InserirClienteAsync(AcessoADados.ServiceReference1.Cliente dadosCliente) {
            return base.Channel.InserirClienteAsync(dadosCliente);
        }
        
        public AcessoADados.ServiceReference1.Funcionario[] ConsultarFuncionarioDataAccess() {
            return base.Channel.ConsultarFuncionarioDataAccess();
        }
        
        public System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Funcionario[]> ConsultarFuncionarioDataAccessAsync() {
            return base.Channel.ConsultarFuncionarioDataAccessAsync();
        }
        
        public AcessoADados.ServiceReference1.Funcionario SelecionarFuncionario(int IdFuncionario) {
            return base.Channel.SelecionarFuncionario(IdFuncionario);
        }
        
        public System.Threading.Tasks.Task<AcessoADados.ServiceReference1.Funcionario> SelecionarFuncionarioAsync(int IdFuncionario) {
            return base.Channel.SelecionarFuncionarioAsync(IdFuncionario);
        }
        
        public void ExcluirFuncionario(int IdFuncionario) {
            base.Channel.ExcluirFuncionario(IdFuncionario);
        }
        
        public System.Threading.Tasks.Task ExcluirFuncionarioAsync(int IdFuncionario) {
            return base.Channel.ExcluirFuncionarioAsync(IdFuncionario);
        }
        
        public void AtualizarFuncionario(AcessoADados.ServiceReference1.Funcionario DadosFuncionario) {
            base.Channel.AtualizarFuncionario(DadosFuncionario);
        }
        
        public System.Threading.Tasks.Task AtualizarFuncionarioAsync(AcessoADados.ServiceReference1.Funcionario DadosFuncionario) {
            return base.Channel.AtualizarFuncionarioAsync(DadosFuncionario);
        }
        
        public void InserirFuncionario(AcessoADados.ServiceReference1.Funcionario DadosFuncionario) {
            base.Channel.InserirFuncionario(DadosFuncionario);
        }
        
        public System.Threading.Tasks.Task InserirFuncionarioAsync(AcessoADados.ServiceReference1.Funcionario DadosFuncionario) {
            return base.Channel.InserirFuncionarioAsync(DadosFuncionario);
        }
        
        public void InserirCompra(string IdFornecedor, string IdCompra, AcessoADados.ServiceReference1.Compra DadosCompra) {
            base.Channel.InserirCompra(IdFornecedor, IdCompra, DadosCompra);
        }
        
        public System.Threading.Tasks.Task InserirCompraAsync(string IdFornecedor, string IdCompra, AcessoADados.ServiceReference1.Compra DadosCompra) {
            return base.Channel.InserirCompraAsync(IdFornecedor, IdCompra, DadosCompra);
        }
    }
}
